### ISSUE TITLE
Problem with Dagger Play

### ISSUE THREAD

**Issue by Madhuparna04** [maticnetwork/eth-dagger.js#22]
In [Dagger Play](https://matic.network/dagger/play) the event config string is automatically converted into lowercase, because of which there is a problem with using the address which is Case Sensitive. Therefore, currently the Dagger commands using address cannot be run with the Dagger Play.

**Comment by Madhuparna04** [comment]
Can I work on this issue?

**Comment by jdkanani** [comment]
@Madhuparna04 Yeah sure, you can work on this :) 

@0xAshish I thought we had fixed this issue before.

**Comment by 0xAshish** [comment]
@Madhuparna04 feel free to open a PR. 😄

**Comment by Madhuparna04** [comment]
As mentioned by @ptsayli the error is because the corresponding functionality is not yet added and not because the input string is being converted to lowercase automatically. So, what do I do?

**Comment by ptsayli** [comment]
In my understanding, @Madhuparna04 is talking about the issue implementation of dagger on Matic website, everything is working fine from dagger side.

closing this PR as this issue has nothing to fix on eth-dagger.
