### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by nsvdev** [maticnetwork/eth-dagger.js#5]
Yo. Very strange behaviour continues to happen over and over: 
When having a line like `_dagger =  new Dagger.default(daggerAddr);` Node crashes with this error:

**Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1060:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)**

If line `_dagger =  new Dagger.default(daggerAddr);` is commented out error is not showing up.

Any ideas how to solve that?

**Comment by nsvdev** [comment]
Guys, it turns out that it is the fault of `mqtts://mainnet.dagger.matic.network` - the domains cert is expired. If using `wss://mainnet.dagger.matic.network` - everything works well.

**Comment by anurag-arjun** [comment]
We are looking into this.

**Comment by jdkanani** [comment]
We have fixed this. @anurag-arjun can you test once and close this if possible?

**Comment by anurag-arjun** [comment]
Tested it and this is fixed.
